version: "3.5"

services:
  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.aws.dexs.com.au`)"
        - "traefik.http.routers.whoami.entrypoints=web"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        # - "traefik.http.routers.whoami.entrypoints=websecure"
        # - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    networks:
      - public
networks:
  public:
    external: true
